name: dart_frog_basic
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.8
  http: ^1.6.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  json_serializable: ^6.11.3
  mocktail: ^1.0.3
  test: ^1.25.5
